// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoy11RZ-Q8M9iFgIgxVmMIOr89JWz39Ok',
    appId: '1:197834349832:web:26939ddc5688c6c24c20bd',
    messagingSenderId: '197834349832',
    projectId: 'mediplants-51454',
    authDomain: 'mediplants-51454.firebaseapp.com',
    storageBucket: 'mediplants-51454.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3aRGkc_twfzpD4MDmszbBLizF1FOQ8iw',
    appId: '1:197834349832:android:033fb751db8e2aa04c20bd',
    messagingSenderId: '197834349832',
    projectId: 'mediplants-51454',
    storageBucket: 'mediplants-51454.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-b9TZQ6ot76hakSursiPb8kvB8CEUk24',
    appId: '1:197834349832:ios:cf981f5299e766964c20bd',
    messagingSenderId: '197834349832',
    projectId: 'mediplants-51454',
    storageBucket: 'mediplants-51454.appspot.com',
    iosClientId: '197834349832-eqcgh2bit98r47lmv879smd5t1c8iqce.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediplantsApp',
  );
}
